export const GENRES = {
  ACTION: 'Action',
  ADVENTURE: 'Adventure',
  ANIMATION: 'Animation',
  BIOGRAPHY: 'Biography',
  COMEDY: 'Comedy',
  CRIME: 'Crime',
  DOCUMENTARY: 'Documentary',
  DRAMA: 'Drama',
  FAMILY: 'Family',
  FANTASY: 'Fantasy',
  HISTORY: 'History',
  HORROR: 'Horror',
  MUSIC: 'Music',
  MUSICAL: 'Musical',
  MYSTERY: 'Mystery',
  REALITY_TV: 'Reality-TV',
  ROMANCE: 'Romance',
  SCI_FI: 'Sci-Fi',
  SPORT: 'Sport',
  THRILLER: 'Thriller',
  WAR: 'War',
  WESTERN: 'Western',
};
