export const SITE_SETTINGS = {
  APP_NAME: 'APP_NAME',
  APP_HOST_NAME: 'APP_HOST_NAME',
  APP_HOST_LOG_PERIOD: 'APP_HOST_LOG_PERIOD',
  APP_HOST_PRIVACY_URL: 'APP_HOST_PRIVACY_URL',
  APP_HOST_GDPR_URL: 'APP_HOST_GDPR_URL',
  APP_FEEDBACK_URL: 'APP_FEEDBACK_URL',
  APP_CODE_URL: 'APP_CODE_URL',
  APP_VERSION: 'APP_VERSION',
};
