name: Build and Deploy

on:
  workflow_dispatch: # Manually triggered

permissions:
  contents: write

jobs:
  deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ./frontend/movies-frontend/package-lock.json
      - run: npm ci
        working-directory: ./frontend/movies-frontend
      - run: npm run build
        working-directory: ./frontend/movies-frontend
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./frontend/movies-frontend/dist # The folder the action should deploy.

